db:
  port: 5435
  password: 39ddkan3a__xfhfheu..33!!
db_instrumentacion:
  host: ip_db_instrumentacion
  user: usuario_admin_db_instrumentacion
  password: pass_db_instrumentacion
  port: port_db_instrumentacion
  database: instrumentacion_db
  schema: instrumentacion
  usuario_backup: usuario_pgpass_para_backups
  usuario_inst_responsable_backup: usuario_inst
log:
  req: false
login:
  plus:
    secret: 39djjfnvvjas..33.3.33
    allowHttpLogin: true
devel:
  forceShowAsEditable: false
client-setup:
  skin: ""
  lang: es
server:
  skins:
    confort:
      local-path: ../backend-skins/dist/
